import Link from "next/link";
import { CONTACT_EMAIL, GOVERNING_STATE, LEGAL_ENTITY, MAILING_ADDRESS, PRODUCT, TERMS_EFFECTIVE } from "@/lib/legal";

export const metadata = { title: "Terms of Service — Storecasted" };

/*
 * DRAFT — have a lawyer review before charging real customers.
 * Written to match what the product actually does. If the product changes
 * (texts, automatic ordering, new integrations), these terms need to change too.
 */
export default function Terms() {
  return (
    <div className="legal">
      <Link href="/" className="auth-back">← {PRODUCT}</Link>
      <h1 className="hero">Terms of Service</h1>
      <p className="legal-meta">Effective {TERMS_EFFECTIVE}</p>

      <p>
        These Terms are an agreement between {LEGAL_ENTITY} (&ldquo;we,&rdquo; &ldquo;us&rdquo;), which operates {PRODUCT},
        and the business that creates an account (&ldquo;you&rdquo;). By creating an account or using {PRODUCT}, you agree
        to these Terms and our <Link href="/privacy">Privacy Policy</Link>.
      </p>

      <h2>1. Who can use {PRODUCT}</h2>
      <p>
        {PRODUCT} is for businesses. You must be at least 18 years old and authorized to agree to these Terms on behalf
        of the business you sign up for. You&apos;re responsible for keeping your login secure and for all activity on
        your account.
      </p>

      <h2>2. What {PRODUCT} does</h2>
      <p>
        {PRODUCT} connects to your Square account with read-only access, analyzes your sales, inventory and related
        data, and gives you briefings, dashboards and suggestions. {PRODUCT} does not change anything in your Square
        account, place orders, contact your suppliers, or move money on your behalf.
      </p>

      <h2>3. Suggestions are estimates — decisions are yours</h2>
      <p>
        Suggested order quantities, stock-out estimates, trends and other insights are estimates based on your past
        data. They are not guarantees and not professional business, financial, accounting or legal advice. In
        particular:
      </p>
      <ul>
        <li>Estimates depend on the accuracy and completeness of the data in your Square account. If your stock counts, prices, costs or categories are wrong or missing, our figures will be too.</li>
        <li>We don&apos;t know how long your suppliers take to deliver, minimum order sizes, case sizes, upcoming promotions, seasonal changes or anything else that isn&apos;t in your data.</li>
        <li>Some wording is generated by artificial intelligence and may contain mistakes.</li>
      </ul>
      <p>
        You are solely responsible for your purchasing, pricing, staffing and other business decisions, including
        whether to follow any suggestion. We aren&apos;t responsible for running out of stock, over-ordering, lost
        sales, or any other outcome of decisions you make.
      </p>

      <h2>4. Your Square connection</h2>
      <p>
        By connecting Square, you authorize us to access your Square data with the permissions shown on Square&apos;s
        consent screen. You can revoke access at any time in your Square account. {PRODUCT} is not made, endorsed or
        supported by Block, Inc. or Square, and your use of Square is governed by your agreement with them.
      </p>

      <h2>5. Free trial, subscription and cancellation</h2>
      <ul>
        <li><b>Free trial.</b> New accounts may receive a free trial. We&apos;ll show you how many days are left inside the app. You won&apos;t be charged during the trial.</li>
        <li><b>Subscription.</b> To keep using {PRODUCT} after a trial, you subscribe at the price shown to you before you pay. Subscriptions are billed in advance at the start of each billing period.</li>
        <li><b>Automatic renewal.</b> Your subscription renews automatically each billing period, and you authorize us (through our payment processor, Stripe) to charge your payment method until you cancel.</li>
        <li><b>Cancel any time.</b> You can cancel online at any time from the Billing page — no phone call or email required. Cancellation takes effect at the end of your current billing period, and you keep access until then.</li>
        <li><b>Refunds.</b> Payments are non-refundable, and we don&apos;t give partial refunds for unused time, except where the law requires otherwise.</li>
        <li><b>Price changes.</b> We&apos;ll give you at least 30 days&apos; notice before a price change affects your subscription, so you can cancel first if you choose.</li>
        <li><b>Failed payments.</b> If a payment fails, we may keep your access for a short period while it&apos;s retried, then suspend it until payment succeeds.</li>
        <li><b>Taxes.</b> Prices don&apos;t include taxes. You&apos;re responsible for any taxes that apply to your purchase.</li>
      </ul>

      <h2>6. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>connect a Square account you aren&apos;t authorized to connect;</li>
        <li>try to access other customers&apos; data, or to bypass billing, security or access controls;</li>
        <li>reverse engineer, scrape, overload or interfere with the service;</li>
        <li>resell or give others access to {PRODUCT} without our written permission; or</li>
        <li>use {PRODUCT} for anything unlawful.</li>
      </ul>

      <h2>7. Your data</h2>
      <p>
        You own your business data. You give us permission to access, store and process it only as needed to run,
        secure, support and improve {PRODUCT}, as described in our <Link href="/privacy">Privacy Policy</Link>. We may
        create aggregated, de-identified statistics that can&apos;t reasonably be used to identify you or your business,
        and use them to improve {PRODUCT}. We don&apos;t sell your data.
      </p>

      <h2>8. Third-party services</h2>
      <p>
        {PRODUCT} relies on third-party services, including Square, Stripe, and our hosting and AI providers. We
        aren&apos;t responsible for their availability, accuracy or actions, and changes they make may affect what
        {PRODUCT} can do.
      </p>

      <h2>9. Changes to {PRODUCT}</h2>
      <p>
        We may add, change or remove features. We don&apos;t guarantee that {PRODUCT} will always be available,
        uninterrupted or error-free.
      </p>

      <h2>10. Ending your account</h2>
      <p>
        You can stop using {PRODUCT} and cancel at any time. We may suspend or close your account if you break these
        Terms, don&apos;t pay, or use {PRODUCT} in a way that could harm us, other customers or third parties. We may
        also discontinue {PRODUCT}; if we do, we&apos;ll give reasonable notice and refund any prepaid fees for time you
        won&apos;t be able to use. Sections 3, 7 and 11–15 continue after your account ends.
      </p>

      <h2>11. Disclaimer of warranties</h2>
      <p className="legal-caps">
        {PRODUCT} is provided &ldquo;as is&rdquo; and &ldquo;as available.&rdquo; To the fullest extent the law allows, we
        disclaim all warranties, express or implied, including warranties of merchantability, fitness for a particular
        purpose, accuracy and non-infringement.
      </p>

      <h2>12. Limitation of liability</h2>
      <p className="legal-caps">
        To the fullest extent the law allows, we will not be liable for any indirect, incidental, special,
        consequential or punitive damages, or for lost profits, lost revenue, lost sales, excess or insufficient
        inventory, or lost data, even if we were told they were possible. Our total liability for any claim relating
        to {PRODUCT} is limited to the greater of the amount you paid us in the 12 months before the claim arose, or
        one hundred U.S. dollars ($100).
      </p>

      <h2>13. Indemnification</h2>
      <p>
        You agree to defend and indemnify {LEGAL_ENTITY} against claims, losses and expenses (including reasonable
        legal fees) arising from your misuse of {PRODUCT}, your breach of these Terms, or your violation of law or of
        someone else&apos;s rights.
      </p>

      <h2>14. Resolving disputes</h2>
      <p>
        <b>Talk to us first.</b> If you have a problem, contact us at {CONTACT_EMAIL} and give us 30 days to try to
        resolve it informally.
      </p>
      <p>
        <b>Arbitration.</b> If we can&apos;t resolve it, any dispute arising from these Terms or {PRODUCT} will be
        resolved by binding individual arbitration administered by the American Arbitration Association under its
        Commercial Arbitration Rules, rather than in court. Either of us may instead bring an individual claim in
        small-claims court if it qualifies.
      </p>
      <p>
        <b>No class actions.</b> You and we each agree to bring claims only individually, not as a plaintiff or class
        member in any class, collective or representative proceeding.
      </p>
      <p>
        <b>Governing law.</b> These Terms are governed by the laws of the State of {GOVERNING_STATE} and applicable U.S.
        federal law, without regard to conflict-of-law rules. Any court proceeding permitted by these Terms will be
        brought in the state or federal courts located in {GOVERNING_STATE}.
      </p>

      <h2>15. General</h2>
      <p>
        These Terms and our Privacy Policy are the entire agreement between us about {PRODUCT}. If any part is found
        unenforceable, the rest still applies. Our not enforcing a provision isn&apos;t a waiver. You may not transfer
        these Terms without our consent; we may transfer them in connection with a merger, acquisition or sale of
        assets. Neither of us is responsible for delays caused by events beyond reasonable control.
      </p>

      <h2>16. Changes to these Terms</h2>
      <p>
        We may update these Terms. If a change is material, we&apos;ll notify you by email or in the app before it takes
        effect. Continuing to use {PRODUCT} after the change means you accept it. If you don&apos;t agree, you can cancel.
      </p>

      <h2>17. Contact</h2>
      <p>
        {LEGAL_ENTITY}<br />
        {MAILING_ADDRESS}<br />
        {CONTACT_EMAIL}
      </p>
    </div>
  );
}
